swupdate changes

diff --git a/videology-distro/recipes-core/initrdscripts/initramfs-framework/init b/videology-distro/recipes-core/initrdscripts/initramfs-framework/init
--- a/videology-distro/recipes-core/initrdscripts/initramfs-framework/init
+++ b/videology-distro/recipes-core/initrdscripts/initramfs-framework/init
@@ -61,9 +61,10 @@ fatal() {
     if [ -n "$bootparam_init_fatal_sh" ]; then
         sh
     else
-    while [ "true" ]; do
-        sleep 3600
-    done
+        # use swupdate as an error fallback
+        echo "yes" > /tmp/swupdate_enabled
+        echo "err" > /tmp/initrd_error
+        eval "swupdate_run"
     fi
 }
 
@@ -149,7 +150,7 @@ for m in $MODULES_DIR/*; do
     fi
 
     debug "Running ${module}_run"
-    eval "${module}_run"
+    eval "${module}_run" || fatal "ERROR: Failed to run module $module"
 
     # post hooks
     for h in $MODULE_POST_HOOKS; do
diff --git a/videology-distro/recipes-core/initrdscripts/initramfs-framework/storage b/videology-distro/recipes-core/initrdscripts/initramfs-framework/storage
--- a/videology-distro/recipes-core/initrdscripts/initramfs-framework/storage
+++ b/videology-distro/recipes-core/initrdscripts/initramfs-framework/storage
@@ -5,7 +5,57 @@ storage_enabled() {
     return 0
 }
 
+function get_slot
+{
+    for i in `cat /proc/cmdline`; do
+        if [[ $i == bootslot=* ]]; then
+            CURRENT_SLOT="${i: -1}"
+        fi;
+    done
+    [ "$CURRENT_SLOT" = "1" ] || CURRENT_SLOT="0";
+}
+
+storage_overlay_hook() {
+	status=$1
+	module=$2
+
+    [ "$module" = "rootfs" ] || return 0
+    debug "storage_overlay_hook running $1 $module"
+
+    get_slot
+    #install modules.squashfs in rootfs
+    if [ -f "/storage/bsp/$CURRENT_SLOT/modules.squashfs" ]; then
+        # mkdir -p /$ROOTFS_DIR/lib/modules
+        mount -t squashfs /storage/bsp/$CURRENT_SLOT/modules.squashfs /$ROOTFS_DIR/lib/modules
+    fi
+
+    mkdir -p /storage/overlay/upper
+    mkdir -p /storage/overlay/work
+    mount -t overlay -o index=off,metacopy=off,lowerdir=$ROOTFS_DIR,upperdir=/storage/overlay/upper,workdir=/storage/overlay/work overlay "$ROOTFS_DIR"
+    if [ $? -ne 0 ]; then
+        echo "Failed to mount overlay for /. Clearing overlay."
+        rm -rf /storage/overlay/upper/*
+        rm -rf /storage/overlay/work/*
+        mount -t overlay -o index=off,metacopy=off,lowerdir=$ROOTFS_DIR,upperdir=/storage/overlay/upper,workdir=/storage/overlay/work overlay "$ROOTFS_DIR"
+    fi
+
+    for f in /storage/config/persist/* ; do
+        cp -fr -t "/$ROOTFS_DIR" "$f"
+    done
+
+    # move the storage mount to the rootfs
+    [ -d /$ROOTFS_DIR/storage ] && mount -n --move /storage "$ROOTFS_DIR/storage"
+}
+
 storage_run() {
+    # add function to add overlay after rootfs
+    add_module_post_hook "storage_overlay_hook"
+
+    # mount boot partition
+    get_slot
+    mkdir -p /boot
+    mount /dev/disk/by-label/boot${CURRENT_SLOT} /boot
+
     mkdir -p /storage
     mount "${STORAGE_DEV}" /storage
 }
